deploy_production:
  image: rrpnarola/docker_git_ftp
  stage: deploy
  environment:
    name: production
    url: https://eros.narola.online:551/pma/shs/data/driverinrome/
  only:
    - development
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - git config git-ftp.url "ftp://$FTP_DEPLOY_HOST/$FTP_PROJECT"
    - git config git-ftp.password "$FTP_DEPLOY_PASSWORD"
    - git config git-ftp.user "$FTP_DEPLOY_USER"
    #- git ftp init
    - git ftp push --remote-root /$FTP_PROJECT/ -vv --syncroot $CI_PROJECT_DIR --user $FTP_DEPLOY_USER --passwd $FTP_DEPLOY_PASSWORD $FTP_DEPLOY_HOST